### PR TITLE
Why does this fork exist?

### PR DESCRIPTION
**Pull request by theFox6**
This is actually less a pull request but more a question...

### CODE REVIEW

**Comment by rautars** [comment]
Planning to ask same question for all Jeija weather mod forks? :) 

Forks can be synced with parent repo anytime, no need to make pull requests. Issue tracker is better place for questions.

**Comment by HybridDog** [comment]
I don't remember why I have this fork.

**Comment by theFox6** [comment]
@xeranas only for those forks that seem useless...

**Comment by theFox6** [comment]
@HybridDog I suggest you delete it if you don't need it...

**Comment by rautars** [comment]
@theFox6 why bothering? there are countless reasons why forks may exist. Many times I making forks for bookmarking / backup reasons. IMO its rather rude to go around and ask/suggest to delete forks.

**Comment by HybridDog** [comment]
If I'd delete it, this discussion is also deleted (or no longer accessible) afaik.

Unfortunately github displays old repositories over new ones if the old ones have more stars, e.g. [PilzAdam's old builtin_item mod when searching](https://github.com/search?utf8=%E2%9C%93&q=builtin_item&type=).

Now that there're repository tags, I can add a don't use tag to my old repositories.

**Comment by theFox6** [comment]
> IMO its rather rude to go around and ask/suggest to delete forks.

true...

> Unfortunately github displays old repositories over new ones if the old ones have more stars,

that's why I asked
never mind

**Comment by rautars** [comment]
> I can add a don't use tag to my old repositories.

@HybridDog there is option to make repository read-only https://help.github.com/articles/archiving-a-github-repository

**Pull request closed without merging**
